### ISSUE TITLE
About transition to federated plugin

### ISSUE THREAD

**Issue by Skyost** [Skyost/Bonsoir#10]
This issue has been created to keep talking about #9. So, as I said in https://github.com/Skyost/Bonsoir/pull/9#issuecomment-793633033, I have done refactoring in cea115abf6b41d20d4674065ca4043b344a3ab1d and 5556a7b1a129c44ba64bdc3ff073cfcd47ec79e5 :

* Moved all source files into the `src` directory.
* Renamed `BonsoirPlatformEvents` into `BonsoirAction` (to avoid confusions with `BonsoirEvent`).
* Merged `MethodChannelBonsoir` and `BonsoirPlatformInterface` because I thought it was not needed to have an abstraction for `BonsoirPlatformInterface` (but I'm not that sure about this one).

What do you think about it @Piero512 ?

**Comment by Piero512** [comment]
This is very bad. 
The merge of platform interface with the method channel is bad, other plug-ins don't necessarily need to use a method channel to implement a platform interface, so it should be separated. See 
https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher_platform_interface/lib as an example.

**Comment by Piero512** [comment]
You might also check out my plugin extending the current platform. https://github.com/Piero512/bonsoir_linux_dbus

**Comment by Skyost** [comment]
> The merge of platform interface with the method channel is bad, other plug-ins don't necessarily need to use a method channel to implement a platform interface, so it should be separated.

I see. I reverted the change in 0b0475ee130edabe9b2e579979628c72555dd049.
