### ISSUE TITLE
ERROR: message sent from native to Flutter on non-platform thread

### ISSUE THREAD

**Issue by Caesarovich** [Skyost/Bonsoir#102]
**Describe the bug**
When using Bonsoir on Windows this error appears in the console:

```
[ERROR:flutter/shell/common/shell.cc(1055)] The 'fr.skyost.bonsoir.broadcast.76232' channel sent a message from native to Flutter on a non-platform thread. 
Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
```

**To Reproduce**
1. Start a discovery
2. Wait some undetermined time

**Expected behavior**
That error shouldn't happen.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Skyost** [comment]
That's not an error, see https://github.com/Skyost/Bonsoir/issues/78#issuecomment-1877140573.

**Comment by Caesarovich** [comment]
Thanks !
