### ISSUE TITLE
channel sent a message from native to Flutter on a non-platform thread.

### ISSUE THREAD

**Issue by XMCodey** [Skyost/Bonsoir#103]
**Fluttert tips on windows**
[ERROR:flutter/shell/common/shell.cc(1065)] The 'fr.skyost.bonsoir.discovery.4311' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See [https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading](https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading) for more information.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows11
 - Version 24H2

**Flutter version**
 Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [版本 10.0.26100.2033], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.5)
[√] Android Studio (version 2024.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

**Comment by Skyost** [comment]
Please see #78.
