### ISSUE TITLE
Cast and Bonsoir

### ISSUE THREAD

**Issue by r2d2Proton** [Skyost/Bonsoir#105]
The build for this (https://pub.dev/packages/cast/example) fails for my Android phone and Pixel tablet. It does work for Windows 11 but not for Android.

PS E:\Dev\Repos\r2d2Proton\flutterTests\casttests> flutter run
Connected devices:
:
Pixel 7 Pro (mobile)  android-arm64  • Android 14 (API 34)
:
[2]: Pixel 7 Pro
[3]: Windows (windows)

Please choose one (or "q" to quit): 2

Launching lib\main.dart on Pixel 7 Pro in debug mode...
e: file:///C:/Users/Jerry/AppData/Local/Pub/Cache/hosted/pub.dev/bonsoir_android-5.1.5/android/src/main/kotlin/fr/skyost/bonsoir/BonsoirPlugin.kt:8:48 Unresolved reference: Registrar
e: file:///C:/Users/Jerry/AppData/Local/Pub/Cache/hosted/pub.dev/bonsoir_android-5.1.5/android/src/main/kotlin/fr/skyost/bonsoir/BonsoirPlugin.kt:21:37 Unresolved reference: Registrar

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bonsoir_android:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 3s
Running Gradle task 'assembleDebug'...                              3.5s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by r2d2Proton** [comment]
pubspec.yaml:

name: casttests
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0-106.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cast: ^2.1.0
  bonsoir: ^5.1.10
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

**Comment by Skyost** [comment]
Hey,

That's an issue with `cast`, not Bonsoir 😅
