### ISSUE TITLE
Phone asking for network permission, but I'm not using Bonsoir

### ISSUE THREAD

**Issue by sgehrman** [Skyost/Bonsoir#11]
I could be wrong about this, but I'm trying to track down this problem.

I have Bonsoir included in a shared lib.  In one app I do use Bonsoir, but in another I never use it.  But iOS is still asking for permission to view the local network?  Does that make any sense? I'll keep investigating.

**Comment by sgehrman** [comment]
oh, it says this message won't show up on release builds.  Ok, nevermind, but if you can fix it, great.

**Comment by Skyost** [comment]
I could check what I can do, but I would need more details please.
