### ISSUE TITLE
Services no longer being discovered after restarting/re-creating BonsoirDiscovery

### ISSUE THREAD

**Issue by rvbiljouw** [Skyost/Bonsoir#16]
**Describe the bug**
Services no longer being discovered after restarting/re-creating BonsoirDiscovery

**To Reproduce**
1. Create BonsoirDiscovery
2. Listen to eventStream
3. Disconnect device from internet
4. Reconnect device to internet
5. Re-create/restart discovery by calling .stop() on the existing instance and creating a new one

**Expected behavior**
I'm expecting to see services getting discovered by Bonsoir upon restarting the discovery but nothing happens. When not restarting discovery the services are also not discovered upon reconnecting to the network.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Motorola e6 play, huawei p20 pro, oneplus 8 pro  
 - OS: Android 8, 9, 10

**Additional context**

**Comment by Skyost** [comment]
Hi, sorry for the delay !

Do you have any stacktrace ?

**Comment by rvbiljouw** [comment]
Afraid not @Skyost, it just results in literally nothing happening - no errors, but also no services being discovered / missing events.

**Comment by rvbiljouw** [comment]
I've had the opportunity to test a couple of other plugins that use NsdManager under the hood and they all seem to be displaying this same issue of service discovery breaking after a network disconnect. Perhaps there is some option on NsdManager that should be enabled to handle this case - I will investigate further.

**Comment by Skyost** [comment]
Thanks for investigating ! Maybe we could listen for network changes (using something like [`connectivity_plus`](https://pub.dev/packages/connectivity_plus)), and properly close the various streams / listeners / ... upon deconnection, and recreate everything once the network goes back to the normal. What do you think about it @rvbiljouw ?

**Comment by carloselborges** [comment]
@Skyost Congrats for the lib... I'm using a lot here.

I'm having the exact same situation as the @rvbiljouw related.

1) Connected to an IOT device on his generated Wifi.
2) After configs, I return to my wifi.
3) No more Mdns services are found after that.
4) After closing the entire app on Android, starts to find services again.

I will investigate more, happens on Android for sure, and I will check if also happens on iOS.

**Comment by bantunes22** [comment]
Any news on this? 
@Skyost did you manage to add  the network change listener?

**Comment by Skyost** [comment]
@bantunes22 There's currently no ETA, sorry.

**Comment by mdev88** [comment]
Same issue here :sweat: . 
Nothing new to add unfortunately. I'll follow this thread in case there's something new to test.

**Comment by Skyost** [comment]
No update here. @Zeeshan0201, does it happen to you when you disconnect from / reconnect to your network ?

**Comment by Zeeshan0201** [comment]
@Skyost thanks for the quick response, the issue recurring while reconnecting...

**Comment by Skyost** [comment]
I think this should do the trick : we listen for network connection changes and stop the discovery / broadcast when disconnected. Would someone here be able to test it ?

**Comment by Zeeshan0201** [comment]
Okay,will check it.
