### ISSUE TITLE
Unable to compile when using master containing bug fix #17

### ISSUE THREAD

**Issue by kultivator-consulting** [Skyost/Bonsoir#18]
**Describe the bug**
The fix for bug #17 does not compile in Kotlin 1.4.32-release-Studio4.1-1 with compile errors.

**To Reproduce**
1. Created new Flutter app using Android Studio.
2. Install flutter_cast (https://github.com/jonathantribouharet/flutter_cast) with updated pubspec.yaml file to use commit 58ca71f of the Bonsoir library which contains the #17 bug fix.
3. Build the Flutter app
4. See error;
e: /Users/dev/Developer/flutter/.pub-cache/git/Bonsoir-58ca71fc769725fff4346caa7422a66ff3a62e20/bonsoir/android/src/main/kotlin/fr/skyost/bonsoir/SuccessObject.kt: (62, 33): None of the following functions can be called with the arguments supplied: 
@InlineOnly public inline fun String(stringBuffer: StringBuffer): String defined in kotlin.text
@InlineOnly public inline fun String(stringBuilder: StringBuilder): String defined in kotlin.text
@InlineOnly public inline fun String(bytes: ByteArray): String defined in kotlin.text
@InlineOnly public inline fun String(chars: CharArray): String defined in kotlin.text

**Expected behavior**
Expect the Flutter app to compile and build successfully.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur version 11.4
 - Browser:
 - Version: 

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5
 - OS: Android
 - Browser:
 - Version:

**Additional context**

**Flutter Doctor:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-NZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.2)

**Comment by Skyost** [comment]
Should be fixed with your pull request (#19).
