### ISSUE TITLE
can't build for ios

### ISSUE THREAD

**Issue by sgehrman** [Skyost/Bonsoir#2]
/Users/steve/.pub-cache/hosted/pub.dartlang.org/bonsoir-0.1.2+1/ios/Classes/BonsoirServiceBrowserDelegate.swift:1:1: Expressions are not allowed at the top level

/Users/steve/.pub-cache/hosted/pub.dartlang.org/bonsoir-0.1.2+1/ios/Classes/BonsoirServiceBrowserDelegate.swift:1:1: Use of unresolved operator '../../'

**Comment by sgehrman** [comment]
same error happens if you open your example project.  
Change the pubspec.yaml to 

  bonsoir: 0.1.2+1

 This seems to work fine
  bonsoir:
    path: ../

**Comment by sgehrman** [comment]
I'm guessing the symlink files aren't working?

**Comment by sgehrman** [comment]
This works:

  bonsoir: 
    git: git://github.com/Skyost/Bonsoir

**Comment by Skyost** [comment]
I think I'm gonna do what `just_audio` does : https://github.com/ryanheise/just_audio/blob/master/example/ios/Podfile.

**Comment by Skyost** [comment]
I think I figured out why it doesn't work. In fact, I created the symlinks using a macOS system and I published the package using a Windows system. The problem with that approach is that [git converts it to a plain text file on Windows](https://stackoverflow.com/questions/5917249/git-symlinks-in-windows).

I'm gonna upload a new version of the package today and tell you if it works.

**Comment by Skyost** [comment]
I've published `0.1.2+2`. It should work now, you should try it out @sgehrman.

**Comment by rostopira** [comment]
I'm having the same issue using version `1.0.1+1`

**Comment by diegoalex** [comment]
> I'm having the same issue using version `1.0.1+1`

Same here.. `1.0.1+1` fixed the Android issue but breaks the IOS build.(`1.0.1` works fine on IOS)

**Comment by Skyost** [comment]
Okay so I'm gonna upload a new version with my macOS system, you'll tell me @rostopira @diegoalex.
