### ISSUE TITLE
Crash on Android KitKat (4.4.2)

### ISSUE THREAD

**Issue by rvbiljouw** [Skyost/Bonsoir#20]
**Describe the bug**
Trying to test a Flutter app using Bonsoir that targets Android KitKat (supported by the framework) results in an exception on startup and app crash.

`E/flutter ( 3691): [ERROR:flutter/lib/ui/ui_dart_state.cc(213)] Unhandled Exception: MissingPluginException(No implementation found for method discovery.initialize on channel fr.skyost.bonsoir)
E/flutter ( 3691): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter ( 3691): <asynchronous suspension>
E/flutter ( 3691): #1      MethodChannelBonsoirAction.ready (package:bonsoir_platform_interface/src/actions/action.dart:67:5)
E/flutter ( 3691): <asynchronous suspension>
E/flutter ( 3691): #2      AutodiscoveryService.start (package:xx/services/autodiscovery.dart:18:5)
E/flutter ( 3691): <asynchronous suspension>
E/flutter ( 3691): #3      main (package:xx/main.dart:13:3)
E/flutter ( 3691): <asynchronous suspension>
E/flutter ( 3691): `

**To Reproduce**

`
  final BonsoirDiscovery discovery  = BonsoirDiscovery(type: '_xx._udp', printLogs: false);
  await discovery.ready;
`

**Expected behavior**
No crash, discovery starts as normal.

**Smartphone (please complete the following information):**
- Samsung Galaxy Pocket Neo S5310 (Android 4.4.2)

**Comment by Skyost** [comment]
It happens sometimes when you don't do a clean build :

```
flutter clean
flutter pub upgrade
flutter run
```

**Comment by Skyost** [comment]
Closed due to inactivity.
