### ISSUE TITLE
When passing attributes on iOS and MacOS will cause value to cover to Optional() string

### ISSUE THREAD

**Issue by FelixYew** [Skyost/Bonsoir#24]
First of all, thanks for the great package.
All the value pass through the attributes will convert to Optional string.
To fix this you may change the code for both iOS and MacOS on :

SwiftBonsoirPlugin.swift
From :
for (key, value) in attributes {
  if (value != nil) {
    result[key] = String(describing: value).data(using: .utf8)
  }
}

To:
for (key, value) in attributes {
  if let value = value {
    result[key] = value.data(using: .utf8)
  }
}

SuccessObject.swift 
From :
for (key, value) in attributes {
  if(value != nil) {
    result[key] = String(decoding: value!, as: UTF8.self)
  }
}

To :
for (key, value) in attributes {
  if let value = value {
    result[key] = String(decoding: value, as: UTF8.self)
  }
}

**Comment by Skyost** [comment]
I think this was fixed in #25.
