### ISSUE TITLE
Why don't you stop Discovery when dispose in BonsoirServiceBrowserDelegate?

### ISSUE THREAD

**Issue by RyoheiTomiyama** [Skyost/Bonsoir#27]
**Describe the bug**

If I repeat bonsoirDiscovery.start and stop, NetServiceBrowser will increase.

![スクリーンショット 2021-09-21 23 47 57](https://user-images.githubusercontent.com/10805686/134194555-358ae9d2-12fb-4ce0-8bd3-deb45ce85e7a.png)

**To Reproduce**
1. `await bonsoirDiscovery.start();`
2. `awaitbonsoirDiscovery.stop();`
3. Repeat 1 and 2.

**Expected behavior**
When bonsoirDiscovery.stop(), you should run browser.stop().

I resolved  the problem in the following way.

BonsoirServiceBrowserDelegate.swift
```swift
    /// Disposes the current class instance.
-   public func dispose(stopDiscovery: Bool = false) {
+   public func dispose(stopDiscovery: Bool = true) {
        services.removeAll()
        onDispose(stopDiscovery)
    }
```

but, I'm not sure if I can change that.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 11 pro, iPhone SE2[e.g. iPhone6]
 - OS: iOS13, 14

**Additional context**

**Comment by track02** [comment]
Hi, was this ever resolved?

We've been using Bonsoir (although an older version ^0.1.3+1) and have noticed that performance seems to drop over time (we start and stop discovery frequently) so just curious if this could be the cause

Many thanks

**Comment by Skyost** [comment]
@track02 Nope, this issue is not closed yet. But yes, it could totally be the cause of your performance problems.

**Comment by track02** [comment]
Thanks for the reply, 

Admittedly not an area I'm familiar with but happy to help if possible

Couple of our observations below if they're of any use:

We see the number of found services decrease over time as the discovery is started/stopped repeatedly and when it is stopped have seen that newly added services can still get discovered 

Disconnecting the device from the network for a few minutes before restarting the app usually seems to clear everything out and behaviour is back to whats expected
