### ISSUE TITLE
Can't get ip address from discovery service

### ISSUE THREAD

**Issue by marco-1988** [Skyost/Bonsoir#28]
Hi

I have a problem with discovery services with this plugin. If I use Debug, I see all attributes of discoveredServices, but if I try to get ip I can't. If Try to save this to variable with var ipAddress = discoveredServices[0].ip I can't use, but can use name, type, port and attributes, but can't use ip.

I don't know if this is a bug or not. Why? Can help me? Thanks.

**Comment by RyoheiTomiyama** [comment]
Hi, macro-1988

Is type of discoveredService ResolvedBonsoirService?
if it is BonsoirService, don't have ip.

check it please.
Or, can you look at the code ?

**Comment by RyoheiTomiyama** [comment]
Hi,  @sureace .

I'm sorry, but I'm not an administrator.
I'm also a user.
I agree that this plugin is great.

As for your question, 192.168.*. * is a private IP.
If Discovery and Broadcast are connected to the same network, I think you can get 192.168.*.,

**Comment by adidevsoft** [comment]
@sureace you might be interested in https://github.com/Skyost/Bonsoir/pull/35/files
