### ISSUE TITLE
Can this package get converted to dart native?

### ISSUE THREAD

**Issue by guyluz11** [Skyost/Bonsoir#36]
Is it necessary for this package to work using flutter components? or can it get converted to Dart native project which can get imported into all Dart supported platforms.

**Comment by Piero512** [comment]
This package depends on Flutter stuff because at the beginning it mostly targeted iOS and Android. 

In theory, packages suited for dart native that won't run on mobile apps, are multicast_dns and such. I've been planning a platform impl for desktop using them but I've been busy.

**Comment by Skyost** [comment]
Answered by @Piero512 👍
