### ISSUE TITLE
_TypeError (type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, String>')

### ISSUE THREAD

**Issue by sgehrman** [Skyost/Bonsoir#4]
Getting this error:  Turn on all exceptions.

Exception has occurred.
_TypeError (type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, String>')

  /// Creates a new resolved Bonsoir service instance from the given JSON map.
  ResolvedBonsoirService.fromJson(Map<String, dynamic> json,
      {String prefix = 'service.'})
      : this(
          name: json['${prefix}name'],
          type: json['${prefix}type'],
          port: json['${prefix}port'],
          attributes: json['${prefix}attributes'],
          ip: json['${prefix}ip'],
        );

**Comment by sgehrman** [comment]
I was using an old build on github I think, trying it again.

**Comment by Skyost** [comment]
Out of curiosity, which build were you using ?

**Comment by DominikStarke** [comment]
I'm also seeing this with 0.1.3
Adding Map.from in resolved_service.dart should fix it:
```
  ResolvedBonsoirService.fromJson(Map<String, dynamic> json,
      {String prefix = 'service.'})
      : this(
          name: json['${prefix}name'],
          type: json['${prefix}type'],
          port: json['${prefix}port'],
          attributes: Map<String, String>.from(json['${prefix}attributes']), // <<<
          ip: json['${prefix}ip'],
        );
```

**Comment by Skyost** [comment]
@DominikStarke Oh, you're testing `0.1.3` from `master` ? That's great 😄

I'm gonna submit a commit in order to fix this one.

**Comment by DominikStarke** [comment]
Yeah, I needed txt-records on iOS. So far it seems to work, if I run the app from xcode. Doesn't work if I run from Flutter directly, but that might be due to some workspace pollution on my side.

Let me know if you need help testing.

**Comment by Skyost** [comment]
@DominikStarke In fact, I may need some testing of that TXT record feature in order to launch a proper release (I haven't had the time so far to run some tests for this, that's why it's not on pub.dev yet). It would be very kind of you if you could run some tests 😄
