### ISSUE TITLE
Deprecation of NetService

### ISSUE THREAD

**Issue by Skyost** [Skyost/Bonsoir#45]
`NetService` has been deprecated in iOS 15.0 and macOS 12.0 ([source](https://developer.apple.com/documentation/foundation/netservice)). We should move on to [`NWBrowser`](https://developer.apple.com/documentation/network/nwbrowser), which is only available since iOS 13.0.

**Comment by chetan-SMRI** [comment]
Hi, I am also having trouble getting this plugin run, I am developing it for iOS 12+ but it is giving me. Same error,

In how much time u think it will be resolved?

**Comment by Skyost** [comment]
@chetan-SMRI It should still work on iOS 12, it's just that NetService will be removed in a future version of iOS.

**Comment by Skyost** [comment]
Just did a little bit of research but had encountered a problem. The Network framework (which is considered to be the replacement of `NetService`) does not support the Bonjour `resolve` operation. This means that we must use the `NetService` API for that.

See : https://developer.apple.com/forums/thread/673771?answerId=662293022#662293022.
