### ISSUE TITLE
Linux version 

### ISSUE THREAD

**Issue by elliotPopina** [Skyost/Bonsoir#46]
Hi thanks for this package, 
do you thinks it's possible to have a linux version of this package ?

**Comment by Skyost** [comment]
@Piero512 has created a Linux version of this package (see [Piero512/bonsoir_linux_dbus](https://github.com/Piero512/bonsoir_linux_dbus)).

**Comment by Piero512** [comment]
Hi @Skyost. It's been a while since I built my linux platform implementation, and I have received timely feedback and even an upgrade to the new platform interface, and I was wondering if maybe you should endorse it. 

Do you have planned updating the platform interface once more?

**Comment by Skyost** [comment]
Hi @Piero512.

> Do you have planned updating the platform interface once more?

Well, the plugin state is the same as before : I love working on it, but I don't have much time to do so and I have other projects to maintain.

I don't know much about DBus / Avahi, so it would be very difficult for me to endorse the development of `bonsoir_linux_dbus`...
