### ISSUE TITLE
Use of undeclared identifier 'BonsoirPlugin'

### ISSUE THREAD

**Issue by nicholasspencer** [Skyost/Bonsoir#50]
**Describe the bug**
The `GeneratedPluginRegistrant` for an iOS or macOS app cannot locate the `BonsoirPlugin` class. It looks like, as of two days ago, the previous objc `BonsoirPlugin` class was removed and only the `SwiftBonsoirPlugin` class exists now. I believe the plugin information in the pubspec of `bonsoir_darwin` needs to be updated to reflect the correct plugin class name.

**To Reproduce**
1. Add `bonsoir` to an iOS or macOS flutter app.
2. Run the app.
3. Observe the generated registrant.

**Expected behavior**
The correct `SwiftBonsoirPlugin` is added to the plugin registry.

**Desktop (please complete the following information):**
 - OS: macOS

**Smartphone (please complete the following information):**
 - OS: iOS (any version)

**Comment by Skyost** [comment]
Thanks ! I've made those changes in order to stop using symlinks on iOS and macOS. I'll merge your pull request and release a new version.
