### ISSUE TITLE
BonsoirDiscovery has null eventStream even after ready

### ISSUE THREAD

**Issue by RubenGarcia** [Skyost/Bonsoir#56]
**Describe the bug**
The code from
https://pub.dev/packages/bonsoir
```
BonsoirDiscovery discovery = BonsoirDiscovery(type: type);
await discovery.ready;
discovery.eventStream!.listen((event) {
  ...
}
```
is sometimes giving me a null eventStream on Android

**To Reproduce**
1 - Do not create any services
2 - Create a discovery 
3 - check the value of eventStream after ready on android.

**Expected behavior**
eventStream is never null
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 12

**Comment by Skyost** [comment]
Do you have an error stacktrace or something like that ?

**Comment by RubenGarcia** [comment]
There is no stack trace, just eventStream is null, which it should not be.

**Comment by Skyost** [comment]
Yes, but I mean, if `eventStream` is null, it means that there is an error occurring at [this line](https://github.com/Skyost/Bonsoir/blob/master/bonsoir_platform_interface/lib/src/actions/action.dart#L72C4-L72C4).

**Comment by RubenGarcia** [comment]
I am using version: "2.2.0+1" so it may be connected to bugs indicated at https://github.com/Skyost/Bonsoir/issues/57

**Comment by Skyost** [comment]
Well, #57 occurs to users who're using a version > 2.0.0+1.
