### ISSUE TITLE
App crashes when using Bonsoir package

### ISSUE THREAD

**Issue by vivekgadgeon** [Skyost/Bonsoir#58]
**Describe the bug**
I installed the package via pubspec.yaml and after running the app it crashes with the following results:
(lldb) 2023-10-18 21:23:08.597088+0530 Runner[338:5105] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
* thread 1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000000000000
error: memory read failed for 0x0
Target 0: (Runner) stopped.

**Smartphone:**
 - Device: iPhone 7
 - OS: iOS 15.7.9
 
**Xcode**
- Version: 15

**Flutter**
- Version: 3.13.7

**Dart**
- Version: 3.1.3

 **Screenshot**
 
<img width="1435" alt="Screenshot 2023-10-18 at 10 31 52 PM" src="https://github.com/Skyost/Bonsoir/assets/138431575/b2107cba-1996-4cbb-9a74-7c2bee6657b5">

**Comment by Skyost** [comment]
Do you have a code snippet or something ? What makes you think it is due to Bonsoir ?

**Comment by vivekgadgeon** [comment]
I just added the package in pubspec.yaml and run the app. Then it crashes. I didn't wrote any code.

**Comment by Skyost** [comment]
And did you try without Bonsoir first ?

**Comment by vivekgadgeon** [comment]
Yes. I tried without Bonsoir and there were no issues.

**Comment by vivekgadgeon** [comment]
I also opened a new project based on the above xcode version and flutter versions with only Bonsoir package. I got the same crash.

**Comment by Skyost** [comment]
I rewrote a lot of the Darwin part recently, please tell me if you're still having the same errors @vivekgadgeon 👍

**Comment by vivekgadgeon** [comment]
I check and it is working now. Thanks for fixing.

**Comment by Skyost** [comment]
Great to hear !
