### ISSUE TITLE
Example link in the documentation leads to a 404

### ISSUE THREAD

**Issue by sarbogast** [Skyost/Bonsoir#68]
**Describe the bug**
I have a weird behavior in iOS discovery and I wanted to test it on a simple example, but the link in the package documentation [there](https://pub.dev/packages/bonsoir) to the [example](https://github.com/Skyost/Bonsoir/tree/master/bonsoir/example) does not seem to exist (anymore?).

**To Reproduce**
1. Go to the [package documentation](https://pub.dev/packages/bonsoir)
2. Click the link to the [example](https://github.com/Skyost/Bonsoir/tree/master/bonsoir/example) 
4. See the 404

**Expected behavior**
I would like to find a reference example that I can use to test the package on both iOS and Android

**Comment by Skyost** [comment]
Oops, my bad !

**Comment by sarbogast** [comment]
Thanks
