### ISSUE TITLE
Can't build for ios (new version bad)

### ISSUE THREAD

**Issue by sgehrman** [Skyost/Bonsoir#7]
/Users/steve/.pub-cache/hosted/pub.dartlang.org/bonsoir-0.1.3+1/ios/Classes/SuccessObject.swift:1:1: error: expressions are not allowed at the top level
    ../../darwin/Classes/SuccessObject.swift
    ^
    /Users/steve/.pub-cache/hosted/pub.dartlang.org/bonsoir-0.1.3+1/ios/Classes/SwiftBonsoirPlugin.swift:1:1: error: expressions are not allowed at the top level
    ../../darwin/Classes/SwiftBonsoirPlugin.swift
    ^
    /Users/steve/.pub-cache/hosted/pub.dartlang.org/bonsoir-0.1.3+1/ios/Classes/BonsoirServiceBrowserDelegate.swift:1:1: error: cannot find operator '../../' in scope
    ../../darwin/Classes/Discovery/BonsoirServiceBrowserDelegate.swift
    ^~~~~~
    /Users/steve/.pub-cache/hosted/pub.dartlang.org/bonsoir-0.1.3+1/ios/Classes/BonsoirServiceBrowserDelegate.swift:1:7: error: cannot find 'darwin' in scope
    ../../darwin/Classes/Discovery/BonsoirServiceBrowserDelegate.swift
          ^~~~~~
    /Users/steve/.pub-cache/hosted/pub.dartlang.org/bonsoir-0.1.3+1/ios/Classes/BonsoirServiceBrowserDelegate.swift:1:14: error: cannot find 'Classes' in scope
    ../../darwin/Classes/Discovery/BonsoirServiceBrowserDelegate.swift
                 ^~~~~~~
    /Users/steve/.pub-cache/hosted/pub.dartlang.org/bonsoir-0.1.3+1/ios/Classes/BonsoirServiceBrowserDelegate.swift:1:22: error: cannot find 'Discovery' in scope
    ../../darwin/Classes/Discovery/BonsoirServiceBrowserDelegate.swift
                         ^~~~~~~~~
    /Users/steve/.pub-cache/hosted/pub.dartlang.org/bonsoir-0.1.3+1/ios/Classes/BonsoirServiceBrowserDelegate.swift:1:32: error: cannot find 'BonsoirServiceBrowserDelegate' in scope
    ../../darwin/Classes/Discovery/BonsoirServiceBrowserDelegate.swift
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/steve/.pub-cache/hosted/pub.dartlang.org/bonsoir-0.1.3+1/ios/Classes/BonsoirServiceDelegate.swift:1:1: error: cannot find operator '../../' in scope
    ../../darwin/Classes/Broadcast/BonsoirServiceDelegate.swift
    ^~~~~~
    /Users/steve/.pub-cache/hosted/pub.dartlang.org/bonsoir-0.1.3+1/ios/Classes/BonsoirServiceDelegate.swift:1:7: error: cannot find 'darwin' in scope
    ../../darwin/Classes/Broadcast/BonsoirServiceDelegate.swift
          ^~~~~~

**Comment by Skyost** [comment]
Oh yes, problem with symlinks. Sorry about that, I'm gonna work on a fix right now.

**Comment by Skyost** [comment]
Should be fixed in 81ccdf8f664e04785fdbd6aa1a5b78a7e8b4b029.

**Comment by rstewart22** [comment]
I'm getting this issue with the latest version, any ideas?

`    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/BonsoirServiceBrowserDelegate.swift:1:1: error: expressions are not allowed at the
    top level
    ../../darwin/Classes/Discovery/BonsoirServiceBrowserDelegate.swift
    ^
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/BonsoirServiceDelegate.swift:1:1: error: expressions are not allowed at the top level
    ../../darwin/Classes/Broadcast/BonsoirServiceDelegate.swift
    ^
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/SuccessObject.swift:1:1: error: expressions are not allowed at the top level
    ../../darwin/Classes/SuccessObject.swift
    ^
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/SwiftBonsoirPlugin.swift:1:1: error: expressions are not allowed at the top level
    ../../darwin/Classes/SwiftBonsoirPlugin.swift
    ^
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/BonsoirServiceBrowserDelegate.swift:1:1: error: cannot find operator '../../' in
    scope
    ../../darwin/Classes/Discovery/BonsoirServiceBrowserDelegate.swift
    ^~~~~~
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/BonsoirServiceBrowserDelegate.swift:1:7: error: cannot find 'darwin' in scope
    ../../darwin/Classes/Discovery/BonsoirServiceBrowserDelegate.swift
          ^~~~~~
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/BonsoirServiceBrowserDelegate.swift:1:14: error: cannot find 'Classes' in scope
    ../../darwin/Classes/Discovery/BonsoirServiceBrowserDelegate.swift
                 ^~~~~~~
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/BonsoirServiceBrowserDelegate.swift:1:22: error: cannot find 'Discovery' in scope
    ../../darwin/Classes/Discovery/BonsoirServiceBrowserDelegate.swift
                         ^~~~~~~~~
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/BonsoirServiceBrowserDelegate.swift:1:32: error: cannot find
    'BonsoirServiceBrowserDelegate' in scope
    ../../darwin/Classes/Discovery/BonsoirServiceBrowserDelegate.swift
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/BonsoirServiceDelegate.swift:1:1: error: cannot find operator '../../' in scope
    ../../darwin/Classes/Broadcast/BonsoirServiceDelegate.swift
    ^~~~~~
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/BonsoirServiceDelegate.swift:1:7: error: cannot find 'darwin' in scope
    ../../darwin/Classes/Broadcast/BonsoirServiceDelegate.swift
          ^~~~~~
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/BonsoirServiceDelegate.swift:1:14: error: cannot find 'Classes' in scope
    ../../darwin/Classes/Broadcast/BonsoirServiceDelegate.swift
                 ^~~~~~~
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/BonsoirServiceDelegate.swift:1:22: error: cannot find 'Broadcast' in scope
    ../../darwin/Classes/Broadcast/BonsoirServiceDelegate.swift
                         ^~~~~~~~~
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/BonsoirServiceDelegate.swift:1:32: error: cannot find 'BonsoirServiceDelegate' in
    scope
    ../../darwin/Classes/Broadcast/BonsoirServiceDelegate.swift
                                   ^~~~~~~~~~~~~~~~~~~~~~
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/SuccessObject.swift:1:1: error: cannot find operator '../../' in scope
    ../../darwin/Classes/SuccessObject.swift
    ^~~~~~
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/SuccessObject.swift:1:7: error: cannot find 'darwin' in scope
    ../../darwin/Classes/SuccessObject.swift
          ^~~~~~
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/SuccessObject.swift:1:14: error: cannot find 'Classes' in scope
    ../../darwin/Classes/SuccessObject.swift
                 ^~~~~~~
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/SuccessObject.swift:1:22: error: cannot find 'SuccessObject' in scope
    ../../darwin/Classes/SuccessObject.swift
                         ^~~~~~~~~~~~~
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/SwiftBonsoirPlugin.swift:1:1: error: cannot find operator '../../' in scope
    ../../darwin/Classes/SwiftBonsoirPlugin.swift
    ^~~~~~
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/SwiftBonsoirPlugin.swift:1:7: error: cannot find 'darwin' in scope
    ../../darwin/Classes/SwiftBonsoirPlugin.swift
          ^~~~~~
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/SwiftBonsoirPlugin.swift:1:14: error: cannot find 'Classes' in scope
    ../../darwin/Classes/SwiftBonsoirPlugin.swift
                 ^~~~~~~
    /Users/richard/.pub-cache/hosted/pub.dartlang.org/bonsoir-1.0.1+1/ios/Classes/SwiftBonsoirPlugin.swift:1:22: error: cannot find 'SwiftBonsoirPlugin' in scope
    ../../darwin/Classes/SwiftBonsoirPlugin.swift`
