### ISSUE TITLE
On iOS, both broadcast and discovery stop immediately after restarting

### ISSUE THREAD

**Issue by sarbogast** [Skyost/Bonsoir#71]
**Describe the bug**
In my app, I start, stop and restart both broadcast and discovery. 
On Android, everything works smoothly as expected. On iOS, everything works as expected the first time, but after I stop and restart either broadcast or discovery, they are immediately stopped without me calling `stop()` on them.

**To Reproduce**
1. Clone [this repository](https://github.com/sarbogast/bonsoir_test)
2. Adapt your signing team
3. Run the app on an iOS device
4. Click Broadcast
5. Click Stop broadcasting
6. Click Broadcast again

**Expected behavior**
If you look at the logs, the first time you start broadcasting, you can see the following series of events:

```
flutter: Serving at http://192.168.1.55:8080
flutter: Broadcast event : BonsoirBroadcastEventType.broadcastStarted
```

And then when you click "Stop broadcasting", you can see this event:
```
flutter: Broadcast event : BonsoirBroadcastEventType.broadcastStopped
```

But then when you click "Broadcast" again, you can see the following:
```
fflutter: Serving at http://192.168.1.55:8080
flutter: Broadcast event : BonsoirBroadcastEventType.broadcastStarted
flutter: Broadcast event : BonsoirBroadcastEventType.broadcastStopped
```

Why does the `broadcastStopped` event happen?

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17.1
 - Version: 5.0.1

**Additional context**
Note that the same thing happens for discovery. But it doesn't happen on Android, neither for broadcast, nor for discovery.

**Comment by Skyost** [comment]
Seems that `broadcast.stop()` is called somewhere. We need to figure out where and why.

**Comment by sarbogast** [comment]
That's interesting. I used to use connectivity_plus to check for connectivity before even starting discovery or broadcasting, and I stopped using it because it was giving me inconsistency `none` connectivity sometimes.

**Comment by sarbogast** [comment]
And apparently it's a [known issue](https://github.com/fluttercommunity/plus_plugins/issues/858).
