### ISSUE TITLE
Error: A value of type 'List<List<int>>' can't be returned from a function with return type 'List<Uint8List>'

### ISSUE THREAD

**Issue by zhahouming** [Skyost/Bonsoir#73]
**Describe the bug**
When I was incorporating this library to build the Android app, I got this error, and it seems to be a platform-specific implementation for Linux, which is a bit unusual

**To Reproduce**
flutter build

**Expected behavior**
build success

**Screenshots**
<img width="858" alt="image" src="https://github.com/Skyost/Bonsoir/assets/16803650/e0aa36a6-6e6a-4d4c-b0af-b3d6ee691fcb">

**Smartphone (please complete the following information):**
 - Device:  OnePlus 8 Pro
 - OS: Android 13

**Additional context**
Flutter 3.13.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ead455963c (9 weeks ago) • 2023-09-26 18:28:17 -0700
Engine • revision a794cf2681
Tools • Dart 3.1.3 • DevTools 2.25.0
 zhahouming@MacBook-Pro  ~/jzxl/codeup/siyouyun_mobile   master ●  fl doctor -v
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.1 22C65 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.13.6 on channel stable at /Users/zhahouming/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (9 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/zhahouming/Library/Android/sdk
    • Platform android-34, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (3 available)
    • IN2020 (mobile) • 457d63cc • android-arm64  • Android 13 (API 33)
    • macOS (desktop) • macos    • darwin-x64     • macOS 13.1 22C65 darwin-x64
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by Skyost** [comment]
I think you should upgrade your version of Flutter (run `flutter upgrade` in a Terminal window).

**Comment by olympea** [comment]
What is the minimum Flutter version required for successful launching without issues with Uint8List?

> I think you should upgrade your version of Flutter (run `flutter upgrade` in a Terminal window).
