### ISSUE TITLE
Resolver cuts attribute keys to 9 characters

### ISSUE THREAD

**Issue by julianscheel** [Skyost/Bonsoir#74]
**Describe the bug**
The `normalizeAttributes` functions cuts attribute keys down to 9 keys. The RFC says ''The key SHOULD be no more than nine characters long.". As it's a "SHOULD" and not a "MUST", I think it's not correct to strictly enforce this.

**To Reproduce**
Discover any service, which has a TXT attribute with a key longer then 9 characters. After "discovery" the full key is shown, after "resolve" the key is cut down to the leading 9 characters.

**Expected behavior**
Always expose the full attribute key, even if the service is not following the the RFC suggestion.

**Additional context**
This is not platform specific, but implemented in the core code.

**Comment by Skyost** [comment]
In fact, I think you're right. Maybe we should leave this as an option via an optionnal parameter for example (as the `BonsoirServiceNormalizer` class is accessible).
