### ISSUE TITLE
Getting the IP/address of BonsoirDiscoveryEvent

### ISSUE THREAD

**Issue by guyluz11** [Skyost/Bonsoir#75]
**Is your feature request related to a problem? Please describe.**
I would like to get the IP address from or in the BonsoirDiscoveryEvent to show the user that information for this device.

**Describe the solution you'd like**
BonsoirDiscoveryEvent to include an address field of IPV4 and IPV6 or a method to get that info from the BonsoirDiscoveryEvent

**Describe alternatives you've considered**
I saw the option in another mDNS package so maybe using that https://pub.dev/packages/nsd#get-ip-addresses-for-service.
Also there is might be a way to get it using ping to the hostname but this is another step and I think should be part of the package.

**Additional context**

**Comment by Skyost** [comment]
Just use `discovery.resolve(service)` to get its IP address.

**Comment by guyluz11** [comment]
It returns Fututre void.

**Comment by Skyost** [comment]
It returns `Future<void>` because it's the call result. The IP is then returned when `discoveryServiceResolved` is triggered. See https://bonsoir.skyost.eu/docs#discover-services.
