### ISSUE TITLE
More pub points

### ISSUE THREAD

**Issue by guyluz11** [Skyost/Bonsoir#76]
We can get more pub points by following the instructions in pub.dev [score page](https://pub.dev/packages/bonsoir/score) 

![image](https://github.com/Skyost/Bonsoir/assets/9304740/f87b18e8-e819-4290-a549-f6e94df7d0ec)

**Comment by Skyost** [comment]
Yeah, it's because of the `format` rule, which I personnally don't like because you can't configure the formatter.

**Comment by Skyost** [comment]
I thought about your comment today, and I think it can be done for the `bonsoir` package as it consists of only three files. This should not be too hard to do.
