### ISSUE TITLE
Example page is not relevent

### ISSUE THREAD

**Issue by guyluz11** [Skyost/Bonsoir#77]
Our current [example page](https://pub.dev/packages/bonsoir/example) in pub.dev does not contain a real example for this package.

A quick fix can even be to take the `Code snippet` section from the readme and just paste it into the correct page.

**Comment by Skyost** [comment]
Sadly, the example tab of pub.dev displays the content of `example/lib/main.dart`. However, the code snippets available on the README are pretty complete.
