### ISSUE TITLE
Federated plugin. 

### ISSUE THREAD

**Issue by Piero512** [Skyost/Bonsoir#8]
**Is your feature request related to a problem? Please describe.**
I am working on a solution powered by Flutter where I use this plugin to discover services in network. I would like to port my app to desktop platforms 

**Describe the solution you'd like**
A refactoring of this plugin where the interface is consistent with the [Federated Plugin specification](https://flutter.dev/go/federated-plugins).  

**Describe alternatives you've considered**
I've considered the posibility of just using the package [multicast_dns](https://pub.dev/packages/multicast_dns) on platforms where the is no Zeroconf daemon running (like on Linuxes without Avahi, or Windows), and on Linux try to locate an Avahi daemon. But I would like to keep my code the same across platforms.

**Additional context**
This would help a lot in my work, and I expect it would help me by allowing me to write a Linux-specific federated plugin. (one that uses Avahi directly, or falls back to multicast_dns, instead of the deprecated and [not always working](https://github.com/lathiat/avahi/issues/276) libdns_sd compat layer ).

**Comment by Skyost** [comment]
> A refactoring of this plugin where the interface is consistent with the Federated Plugin specification.

This will take a lot of time and a lot of work 😁

**Comment by Piero512** [comment]
Well, today I tried to give it a go and the only issue is that the Discovery and Broadcast classes are subclass of BonsoirClass, which tightly bounds and limits the posibility of creating a platform-independent abstraction where code/flutter selects the impl at buildtime. The rest of classes are basically data classes and can be placed in a package very easily.

**Comment by Skyost** [comment]
Cool, I will closely follow your progress on #9 then 😉

**Comment by Piero512** [comment]
The thing is that i am not sure how not make too much breakage 🤔 That's why I'm sharing the code.

**Comment by Piero512** [comment]
@Skyost I would really like if you check out my PR and tell me any problems you have with it

**Comment by Skyost** [comment]
Yes I know, I'm very sorry for the delay. It should done today or tomorrow.
