### ISSUE TITLE
Crash when TXT record contains empty properties

### ISSUE THREAD

**Issue by foxik0169** [Skyost/Bonsoir#81]
When resolving device, if txt record of broadcast contains attribute that is set to empty ("propertyName="), the BonsoirDevice fails in constructor with NullReferenceException. This happens because String() constructor can not be called with null.

I would expect empty string to be used there without crash.

Used bonsoir 5.1.5 on **Android**.

**Comment by clintpurser** [comment]
also running into this.

**Comment by Skyost** [comment]
Hey,

Thanks for reporting. In the future, please also provide a stacktrace. It really saves a lot of time for debugging problems like this 🙂
