### ISSUE TITLE
How can I run this on native android?

### ISSUE THREAD

**Issue by danielgomezrico** [Skyost/Bonsoir#87]
**Is your feature request related to a problem? Please describe.**
I have the server writen in flutter and it will run this but I want my clients to be android native and I cant find a way to run other libraries that connects to this one

**Describe the solution you'd like**
Provide a native android implementation to use on native android, so they can talk with flutter server apps

**Describe alternatives you've considered**
Im not sure

**Additional context**
Thanks for this library

**Comment by Skyost** [comment]
You can already run this library on native Android (https://github.com/Skyost/Bonsoir/tree/master/packages/bonsoir_android).

**Comment by danielgomezrico** [comment]
How can I add it there?

**Comment by Skyost** [comment]
It's automatically included when you add Bonsoir to your project.

**Comment by danielgomezrico** [comment]
I mean, if I have a native android project that does not have any flutter involved, how can I add it?

**Comment by Skyost** [comment]
You can't, but this is a Flutter library.

**Comment by danielgomezrico** [comment]
I was wondering that it could be possible since the android implemenation is already done... that maybe one way to go is to move that into a separate place and reuse it from here, and then we can have a native android implementation and also a flutter implementation 🤔

**Comment by Skyost** [comment]
Yes it can be done, but why don't you directly use NSD if you're only targetting Android ?
