### ISSUE TITLE
Does not work for Flutter-Tizen project

### ISSUE THREAD

**Issue by phuocbitmark** [Skyost/Bonsoir#88]
**Describe the bug**
When i
await broadcast.start();
-> it throws error
Error broadcasting bonsoir: MissingPluginException(No implementation found for method broadcast.initialize on channel fr.skyost.bonsoir)

**To Reproduce**
1. create Flutter-Tizen project
2. Broadcast

I wonder if this can work on Samsung Tv running TizenOS

**Comment by Skyost** [comment]
Sadly, it's out of the scope. Bonsoir has been designed to run on all platforms supported by Flutter _except Web_.
