### ISSUE TITLE
Specific characters are missing 

### ISSUE THREAD

**Issue by heiha100** [Skyost/Bonsoir#90]
**Describe the bug**
I put a string: 'hello的macbook' in attributes of BonsoirService, but resolved result gets wrong string of 'hello的macbo', the characters of 'ok' are missing.
**To Reproduce**
You could modify the example of this repo to reproducing bug.
1. open `app_service.dart`, and modify the attribute of `os` to 'hello的macbook'
2. run app and resolve the service of current device
3. you could see wrong `os` with 'hello的macbo'

**Expected behavior**
The resolved attributes should keep same with passing in.

**Screenshots**
<img width="611" alt="image" src="https://github.com/Skyost/Bonsoir/assets/134051067/b8d12265-6fcc-4025-beda-1c05099da486">

<img width="795" alt="image" src="https://github.com/Skyost/Bonsoir/assets/134051067/c96d07f4-2760-4f0a-82fc-87aa3142d8d1">

**Desktop (please complete the following information):**
 - OS: macos
 - Version 14.1.2 (23B92)

**Comment by Skyost** [comment]
Hey,

It looks like a problem with key/value length limit :

```
Each constituent string of a DNS TXT record is limited to 255 bytes.
```

Attributes [are normalized](https://github.com/Skyost/Bonsoir/blob/master/packages/bonsoir_platform_interface/lib/src/service/normalizer.dart#L105) to comply with this.

**Comment by heiha100** [comment]
> Hey,
> 
> It looks like a problem with key/value length limit :
> 
> ```
> Each constituent string of a DNS TXT record is limited to 255 bytes.
> ```
> 
> Attributes [are normalized](https://github.com/Skyost/Bonsoir/blob/master/packages/bonsoir_platform_interface/lib/src/service/normalizer.dart#L105) to comply with this.

I don't think so. Because it's only occurs on macos, and I try modify 'os' on android, everything is ok.
<img width="676" alt="image" src="https://github.com/Skyost/Bonsoir/assets/134051067/64fd07f5-a268-4696-a818-149b7ae793ef">
