### ISSUE TITLE
Crashes on iOS caused by DNSServiceProcessResult

### ISSUE THREAD

**Issue by foxik0169** [Skyost/Bonsoir#91]
**Describe the bug**
When calling resolve on a lot services (10+) on iOS there is potential for a crash in DNSServiceProcessResult() function. This can happen because the underlying socket is not available anymore. To fix this, I've implemented asynchronous socket access with DispatchSourceRead. The code can be seen in my fork https://github.com/foxik0169/Bonsoir/tree/5.1.9-stream. There are more changes because I went ahead and make the DNSServiceProcessResult() call work concurently and then send the messages to Flutter on main thread.

**To Reproduce**
Part of the issue is that is not easily reproducible. For my network setup (hotspot on PC and 3 wifi devices connected) it did not happen at all. However when on a wifi that contains a lot of services (10+) with the type that I am trying to resolve, it _might_ crash. All these devices _are being resolved_ at the same time.

**Expected behavior**
No crashes in the native code.

**Screenshots**
![image](https://github.com/Skyost/Bonsoir/assets/6134740/f1d54ab4-80d6-4e42-af00-e3e6c143c4c8)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 17.4.1

**Comment by Skyost** [comment]
Hey,

Great, this could even be related to #89. Feel free to open a PR once you're ready 🙂

**Comment by heiha100** [comment]
> **Describe the bug** When calling resolve on a lot services (10+) on iOS there is potential for a crash in DNSServiceProcessResult() function. This can happen because the underlying socket is not available anymore. To fix this, I've implemented asynchronous socket access with DispatchSourceRead. The code can be seen in my fork https://github.com/foxik0169/Bonsoir/tree/5.1.9-stream. There are more changes because I went ahead and make the DNSServiceProcessResult() call work concurently and then send the messages to Flutter on main thread.
> 
> **To Reproduce** Part of the issue is that is not easily reproducible. For my network setup (hotspot on PC and 3 wifi devices connected) it did not happen at all. However when on a wifi that contains a lot of services (10+) with the type that I am trying to resolve, it _might_ crash. All these devices _are being resolved_ at the same time.
> 
> **Expected behavior** No crashes in the native code.
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/6134740/320419823-f1d54ab4-80d6-4e42-af00-e3e6c143c4c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzI0MjQsIm5iZiI6MTcxMjczMjEyNCwicGF0aCI6Ii82MTM0NzQwLzMyMDQxOTgyMy1mMWQ1NGFiNC04MGQ2LTRlNDItYWYwMC1lM2U2YzE0M2M0YzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTBUMDY1NTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTE1NTI2ODhiM2Q4NDQ0MjY0NzcyNDYxMWFiYTAzZmI3NDQxZGNiZDEwNmYyMzE4NDU2OTcyM2NkNzhmMDA1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eenPyOcF6kPZhupExhh8tZq4s5iKy0lT5GdYfFRrovs)
> 
> **Smartphone (please complete the following information):**
> 
> * Device: iPhone 12
> * OS: iOS 17.4.1

hey, I am facing the same problem. And Thanks for your solution. Would you open a PR for this issue🩷
