### ISSUE TITLE
How to get the IP of the resolved service?

### ISSUE THREAD

**Issue by jonnybrooks** [Skyost/Bonsoir#96]
Hi there! First of all thanks for making this package, it works super great OOTB. 

The only trouble I'm having is how to get the IP of the published service after resolving it... doing a code search, I see that `service.ip` was updated to `service.host`, but when I print out `service.host` it isn't an IP address but the host name like "Android.local."

Any help would be much appreciated!

**Comment by Skyost** [comment]
Hey,

Why do you want to resolve a service host ? Most of the time you only need an host 🙂

**Comment by jonnybrooks** [comment]
Hey @Skyost, thanks for the reply! How is it possible to query the service without an IP? Sorry for the n00b question, but I thought the host name was just "superficial" - so it's possible to make an http request like: `http://Android.local:3000/` or something?

**Comment by Skyost** [comment]
Sorry for the delay, I was super busy until last week. Yep, you can totally make your requests to `homeassistant.local` instead of `192.168.1.100` 🙂

**Comment by jonnybrooks** [comment]
That's so cool! Thank you very much. Can't wait to try this out :D

**Comment by ptrckdev** [comment]
Not to reopen this ticket but we have a swarm of devices that we need to access with their IP to send requests to. The rest of our app only supports talking to the devices with their IP and I dont really want to rewrite this part as i dont even know if I can talk to these devices via their host. Is there a way to revert these changes or add the IP back ot the result set, or am I now stuck with a lower version of your package?

**Comment by Skyost** [comment]
@ptrckdev Sadly, it's not planned to resolve the hostname in order to return the IP address. You should be able to do that [in Dart](https://api.dart.dev/stable/2.7.1/dart-io/InternetAddress/lookup.html) tho.

**Comment by Skyost** [comment]
@ptrckdev This package had this feature in a previous version, but it was :
1. not working on all platforms ;
2. on some other platforms, relying on hacks and workarounds ;
3. in my opinion, pretty useless (if you have the hostname, then you can have the IP address if you _really_ need it).
