### ISSUE TITLE
[Windows] Crash when BonsoirDiscovery start failed

### ISSUE THREAD

**Issue by heiha100** [Skyost/Bonsoir#98]
**Describe the bug**

**To Reproduce**
1. forbiden Dnscache service on windows
2. start bonsoir demo
3. start discovery service
4. see error in "windows event manager" or %LOCALAPPDATA%\CrashDumps when crash dump is enabled

**Expected behavior**
App should run normally event BonsoirDiscovery start failed

**Screenshots**
<img width="876" alt="image" src="https://github.com/Skyost/Bonsoir/assets/134051067/147679df-3e90-42fe-91d1-e69c6c35a2da">
exception is throwed by this line

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Win10

**Additional context**
EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007fffa0aed823 (bonsoir_windows_plugin!thunk@7fffa0ae7676+0x00000000000061ad)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000000000000000
Attempt to read from address 0000000000000000

PROCESS_NAME:  flix.exe

READ_ADDRESS:  0000000000000000 

ERROR_CODE: (NTSTATUS) 0xc0000005 - 0x%p            0x%p                    %s

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000000

EXCEPTION_PARAMETER2:  0000000000000000

STACK_TEXT:  
00000043`2ff5e5f0 00007fff`a0afc1e2     : 000001c4`f3c1b6f8 000001c4`f3c1b6f8 000001c4`f3c1b6f0 000001c4`00000024 : bonsoir_windows_plugin!thunk@7fffa0ae7676+0x61ad
00000043`2ff5e7b0 00007fff`a0afcb7f     : 000001c4`82e6b528 00000043`2ff5eb50 00000043`2ff5ebc8 000001c4`82e6b520 : bonsoir_windows_plugin!std::_Non_trivial_move_assign<std::_Variant_destroy_layer_<std::monostate,bool,int,__int64,double,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::vector<unsigned char,std::allocator<unsigned char> >,std::vector<int,std::allocator<int> >,std::vector<__int64,std::allocator<__int64> >,std::vector<double,std::allocator<double> >,std::vector<flutter::EncodableValue,std::allocator<flutter::EncodableValue> >,std::map<flutter::EncodableValue,flutter::EncodableValue,std::less<flutter::EncodableValue>,std::allocator<std::pair<flutter::EncodableValue const ,flutter::EncodableValue> > >,flutter::CustomEncodableValue,std::vector<float,std::allocator<float> > >,std::monostate,bool,int,__int64,double,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::vector<unsigned char,std::allocator<unsigned char> >,std::vector<int,std::allocator<int> >,std::vector<__int64,std::allocator<__int64> >,std::vector<double,std::allocator<double> >,std::vector<flutter::EncodableValue,std::allocator<flutter::EncodableValue> >,std::map<flutter::EncodableValue,flutter::EncodableValue,std::less<flutter::EncodableValue>,std::allocator<std::pair<flutter::EncodableValue const ,flutter::EncodableValue> > >,flutter::CustomEncodableValue,std::vector<float,std::allocator<float> > >::_Non_trivial_move_assign<std::_Variant_destroy_layer_<std::monostate,bool,int,__int64,double,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::vector<unsigned char,std::allocator<unsigned char> >,std::vector<int,std::allocator<int> >,std::vector<__int64,std::allocator<__int64> >,std::vector<double,std::allocator<double> >,std::vector<flutter::EncodableValue,std::allocator<flutter::EncodableValue> >,std::map<flutter::EncodableValue,flutter::EncodableValue,std::less<flutter::EncodableValue>,std::allocator<std::pair<flutter::EncodableValue const ,flutter::EncodableValue> > >,flutter::CustomEncodableValue,std::vector<float,std::allocator<float> > >,std::monostate,b+0x22
00000043`2ff5e9f0 00007fff`a0afb496     : 00000000`00000000 000001c4`82e6b520 00000043`2ff5ea20 00000000`00000000 : bonsoir_windows_plugin!std::_Variant_storage_<0,bool,int,__int64,double,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::vector<unsigned char,std::allocator<unsigned char> >,std::vector<int,std::allocator<int> >,std::vector<__int64,std::allocator<__int64> >,std::vector<double,std::allocator<double> >,std::vector<flutter::EncodableValue,std::allocator<flutter::EncodableValue> >,std::map<flutter::EncodableValue,flutter::EncodableValue,std::less<flutter::EncodableValue>,std::allocator<std::pair<flutter::EncodableValue const ,flutter::EncodableValue> > >,flutter::CustomEncodableValue,std::vector<float,std::allocator<float> > >::_Variant_storage_<0,bool,int,__int64,double,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::vector<unsigned char,std::allocator<unsigned char> >,std::vector<int,std::allocator<int> >,std::vector<__int64,std::allocator<__int64> >,std::vector<double,std::allocator<double> >,std::vector<flutter::EncodableValue,std::allocator<flutter::EncodableValue> >,std::map<flutter::EncodableValue,flutter::EncodableValue,std::less<flutter::EncodableValue>,std::allocator<std::pair<flutter::EncodableValue const ,flutter::EncodableValue> > >,flutter::CustomEncodableValue,std::vector<float,std::allocator<float> > ><6,std::vector<int,std::allocator<int> >,0>+0x1f
00000043`2ff5ea20 00007fff`a0afcb37     : 00000000`00000000 000001c4`8313acf0 00000000`00000040 00000043`2ff5eb50 : bonsoir_windows_plugin!std::_Variant_storage_<0,std::vector<double,std::allocator<double> >,std::vector<flutter::EncodableValue,std::allocator<flutter::EncodableValue> >,std::map<flutter::EncodableValue,flutter::EncodableValue,std::less<flutter::EncodableValue>,std::allocator<std::pair<flutter::EncodableValue const ,flutter::EncodableValue> > >,flutter::CustomEncodableValue,std::vector<float,std::allocator<float> > >::_Variant_storage_<0,std::vector<double,std::allocator<double> >,std::vector<flutter::EncodableValue,std::allocator<flutter::EncodableValue> >,std::map<flutter::EncodableValue,flutter::EncodableValue,std::less<flutter::EncodableValue>,std::allocator<std::pair<flutter::EncodableValue const ,flutter::EncodableValue> > >,flutter::CustomEncodableValue,std::vector<float,std::allocator<float> > ><4,std::vector<float,std::allocator<float> > const &,0>+0x26
00000043`2ff5eb30 00007fff`a0b01d91     : 000001c4`82f36490 000001c4`82f36490 00000043`2ff5ed68 00000000`0000000b : bonsoir_windows_plugin!std::_Variant_storage_<0,std::monostate,bool,int,__int64,double,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::vector<unsigned char,std::allocator<unsigned char> >,std::vector<int,std::allocator<int> >,std::vector<__int64,std::allocator<__int64> >,std::vector<double,std::allocator<double> >,std::vector<flutter::EncodableValue,std::allocator<flutter::EncodableValue> >,std::map<flutter::EncodableValue,flutter::EncodableValue,std::less<flutter::EncodableValue>,std::allocator<std::pair<flutter::EncodableValue const ,flutter::EncodableValue> > >,flutter::CustomEncodableValue,std::vector<float,std::allocator<float> > >::_Variant_storage_<0,std::monostate,bool,int,__int64,double,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::vector<unsigned char,std::allocator<unsigned char> >,std::vector<int,std::allocator<int> >,std::vector<__int64,std::allocator<__int64> >,std::vector<double,std::allocator<double> >,std::vector<flutter::EncodableValue,std::allocator<flutter::EncodableValue> >,std::map<flutter::EncodableValue,flutter::EncodableValue,std::less<flutter::EncodableValue>,std::allocator<std::pair<flutter::EncodableValue const ,flutter::EncodableValue> > >,flutter::CustomEncodableValue,std::vector<float,std::allocator<float> > ><6,std::vector<unsigned char,std::allocator<unsigned char> >,0>+0x47
00000043`2ff5eba0 00007fff`9ef27a49     : 00000000`00000002 00007ff8`2677b86b 00000000`001b0026 000001c4`e5d63710 : bonsoir_windows_plugin!std::operator<<<std::char_traits<char> >+0x251
00000043`2ff5ecb0 00007fff`9e7059a8     : 00000000`00000000 00000000`00000010 00000000`00000008 00000000`00000002 : flutter_windows!FlutterDesktopTextureRegistrarMarkExternalTextureFrameAvailable+0x8245f9
00000043`2ff5ed40 00007fff`9e7b7b1f     : 00000043`2ff5efc0 000001c4`f3af7a40 00000000`00000000 00007fff`9e7159e3 : flutter_windows!FlutterDesktopTextureRegistrarMarkExternalTextureFrameAvailable+0x2558
00000043`2ff5eef0 00007fff`9e7c4580     : 000001c4`8306ab10 000001c4`e5d00000 00000000`00000000 00000000`00000000 : flutter_windows!FlutterDesktopTextureRegistrarMarkExternalTextureFrameAvailable+0xb46cf
00000043`2ff5ef70 00007fff`9e7c451e     : 000001c4`f3af7c10 00007fff`9f445e90 000001c4`f3127af8 000001c4`f30beb10 : flutter_windows!FlutterDesktopTextureRegistrarMarkExternalTextureFrameAvailable+0xc1130
00000043`2ff5efa0 00007fff`9e7c4c9e     : 00000043`2ff5f158 00007fff`9f3e6bd7 000001c4`f3af7c10 00000000`00000000 : flutter_windows!FlutterDesktopTextureRegistrarMarkExternalTextureFrameAvailable+0xc10ce
00000043`2ff5efe0 00007fff`9e7c1bbd     : 00000000`00000402 00007ff8`00000000 000001c4`e5d29140 000001c4`f3127aa0 : flutter_windows!FlutterDesktopTextureRegistrarMarkExternalTextureFrameAvailable+0xc184e
00000043`2ff5f020 00007fff`9e7c31a9     : 00000002`00000002 00007ff8`26775ba1 00000000`00000002 00007ff8`2677b86b : flutter_windows!FlutterDesktopTextureRegistrarMarkExternalTextureFrameAvailable+0xbe76d
00000043`2ff5f1d0 00007fff`9e7b080c     : 00000000`00000000 000001c4`e5ca7b00 000001c4`e5d290f0 000001c4`e5ca0000 : flutter_windows!FlutterDesktopTextureRegistrarMarkExternalTextureFrameAvailable+0xbfd59
00000043`2ff5f220 00007fff`9e7071d9     : 00000000`00000010 000001c4`e5ca0d20 00000000`00000000 00000000`00000000 : flutter_windows!FlutterDesktopTextureRegistrarMarkExternalTextureFrameAvailable+0xad3bc
00000043`2ff5f250 00007fff`9e71a7c1     : 00000000`00000000 00000000`00000000 000001c4`e5d29140 00000043`2ff5f448 : flutter_windows!FlutterDesktopTextureRegistrarMarkExternalTextureFrameAvailable+0x3d89
00000043`2ff5f390 00007fff`9e71c025     : 00000000`ffffffeb 00000000`00040a02 00000043`2ff5f7e0 00007ff8`25f902aa : flutter_windows!FlutterDesktopTextureRegistrarMarkExternalTextureFrameAvailable+0x17371
00000043`2ff5f420 00007fff`9e71c10d     : 00000000`00030000 00000000`00000001 00000000`80000022 00000000`00040a02 : flutter_windows!FlutterDesktopTextureRegistrarMarkExternalTextureFrameAvailable+0x18bd5
00000043`2ff5f4a0 00007ff8`25f8ef5c     : 00000043`2ff5f7e0 0000dbf9`8d1e5aee 00000000`00000001 00000000`00040a02 : flutter_windows!FlutterDesktopTextureRegistrarMarkExternalTextureFrameAvailable+0x18cbd
00000043`2ff5f4d0 00007ff8`25f8e684     : 00000000`00000000 00007fff`9e71c0a0 00000043`30123800 00007ff8`25fa267e : user32!UserCallWinProcCheckWow+0x50c
00000043`2ff5f660 00007ff7`f6372856     : 00007fff`9e71c0a0 00000000`00000001 00000000`00000000 00007ff8`2679cc70 : user32!DispatchMessageWorker+0x494
00000043`2ff5f6e0 00007ff7`f641d692     : 00000000`00000000 00000000`00000000 00000000`00000001 00007ff8`2679cc70 : flix!wWinMain+0x256
00000043`2ff5f900 00007ff8`26667344     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : flix!__scrt_common_main_seh+0x106
00000043`2ff5f940 00007ff8`2679cc91     : 00000000`004e004c 000001c4`e5bc0100 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x14
00000043`2ff5f970 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21

**Comment by Skyost** [comment]
Thanks for reporting and submitting a PR ! I'll review it soon.
